
CREATE TABLE IF NOT EXEISTS NOBEL _WIN (
   YEAR INTEGER,
   WINNER TEXT,
   SUBJECT TEXT,
   CATEGOREY TEXT
);

INSERT INTO NOBEL-WIN (YEAR, SUBJECT, WINNER,COUNTRY, CATEGORY) VALUES
  (1970, 'PHYSICS', 'AYAAN GUPTA ','NEPAL' , 'SCIENTIST'),
  (1970, 'PHYSICS', 'BIKASH GUPTA ','NEPAL' , 'SCIENTIST'),
  (1970, 'PHYSICS', 'RAMASH GUPTA ','NEPAL' , 'SCIENTIST'),
  (1970, 'PHYSICS', 'AVATAR GUPTA ','NEPAL' , 'SCIENTIST'),
  (1970, 'PHYSICS', 'YUNIK GUPTA ','NEPAL' , 'SCIENTIST'),
  (1970, 'PHYSICS', 'MANAV GUPTA ','NEPAL' , 'SCIENTIST'),
  (1970, 'PHYSICS', 'KAIA GUPTA ','NEPAL' , 'SCIENTIST'),
  (1970, 'PHYSICS', 'LIA GUPTA ','NEPAL' , 'SCIENTIST'),
  (1970, 'PHYSICS', 'AIL GUPTA ','NEPAL' , 'SCIENTIST'),



  SELECT *
  FROM NOBEL_WIN 
  WHERE SUBJECT NOT LIKE 'P%';
  

  