CREATE TABLE IF NOT EXISTS PRODUCT(
  PRODUCT_TO IEXT,
  PRODUCT_NAME TEXT,
  SUPPLIER_ID TEXT,
  CATEGORY_ID TEXT
  UNIT TEXT,
  PRICE RELEASE
);


INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT, PRICE) VALUES
  ('1', 'CHAIR','1','1','10 BOXES*20 BAGS', 180),
  ('2', 'CHANG' ,'1','1', 
